import type { UtilityDefinition, UtilityInputDefinition } from "@/lib/utilities/contracts";

export const fuelTripInputOrder = [
  "fuel-trip-distance",
  "fuel-trip-consumption",
  "fuel-trip-price",
  "fuel-trip-type",
  "fuel-trip-tolls",
  "fuel-trip-passengers",
] as const;

export const fuelTripInputs = {
  consumption: {
    errorMessages: {
      invalid: "Enter a valid fuel consumption.",
      min: "Fuel consumption must be greater than zero.",
      required: "Enter your vehicle's fuel consumption.",
    },
    helpText: "Use your vehicle's expected consumption for this journey.",
    id: "fuel-trip-consumption",
    inputMode: "decimal",
    label: "Fuel consumption",
    min: 0.01,
    required: true,
    step: 0.01,
    type: "number",
    unit: "L/100 km",
  },
  distance: {
    errorMessages: {
      invalid: "Enter a valid trip distance.",
      min: "Trip distance must be greater than zero.",
      required: "Enter the one-way trip distance.",
    },
    helpText: "Enter the one-way road distance. Return trips are doubled automatically.",
    id: "fuel-trip-distance",
    inputMode: "decimal",
    label: "One-way trip distance",
    min: 0.01,
    required: true,
    step: 0.01,
    type: "number",
    unit: "km",
  },
  passengers: {
    errorMessages: {
      invalid: "Enter a whole number of passengers.",
      min: "Include at least one person.",
      required: "Enter the number of people sharing the cost.",
    },
    helpText: "Include the driver in the number of people sharing the trip cost.",
    id: "fuel-trip-passengers",
    inputMode: "numeric",
    label: "People sharing the cost",
    min: 1,
    required: true,
    step: 1,
    type: "number",
    unit: "people",
  },
  price: {
    errorMessages: {
      invalid: "Enter a valid fuel price.",
      min: "Fuel price cannot be negative.",
      required: "Enter the fuel price per litre.",
    },
    helpText: "Use the current price in your currency. Results use the same currency.",
    id: "fuel-trip-price",
    inputMode: "decimal",
    label: "Fuel price per litre",
    min: 0,
    required: true,
    step: 0.001,
    type: "currency",
    unit: "per litre",
  },
  tolls: {
    errorMessages: {
      invalid: "Enter a valid toll cost.",
      min: "Toll cost cannot be negative.",
    },
    helpText: "Optional. Enter the total tolls for the complete journey, including the return leg when relevant.",
    id: "fuel-trip-tolls",
    inputMode: "decimal",
    label: "Total toll cost",
    min: 0,
    required: false,
    step: 0.01,
    type: "currency",
    unit: "your currency",
  },
  tripType: {
    errorMessages: {
      invalid: "Choose one-way or return.",
      required: "Choose one-way or return.",
    },
    id: "fuel-trip-type",
    label: "Journey type",
    required: true,
    type: "radio",
  },
} satisfies Record<string, UtilityInputDefinition>;

export const fuelTripDefinition = {
  analyticsEligibility: {
    allowResultClassification: false,
    allowedCommercialCapabilityIds: [],
    allowedErrorCodes: [],
    allowedEvents: [],
    allowedFieldIds: [],
    allowedInteractionSources: [],
    allowedResultTypes: [],
    ownerApprovalReference: "rapid-plan-build-2026-07-16",
    reviewedDate: "2026-07-16",
  },
  assumptions: [
    "Distance and consumption remain constant across the journey.",
    "Tolls are the whole-journey amount entered by the user and are not doubled automatically.",
    "The total is divided equally across all people entered, including the driver.",
  ],
  calculationVersion: 1,
  commercialEligibility: [],
  contentVersion: 1,
  inputs: [
    fuelTripInputs.distance,
    fuelTripInputs.consumption,
    fuelTripInputs.price,
    fuelTripInputs.tripType,
    fuelTripInputs.tolls,
    fuelTripInputs.passengers,
  ],
  methodology: {
    assumptions: [
      "The entered distance is one-way.",
      "An empty toll field means no toll amount is included.",
      "All monetary inputs and outputs use the same user-chosen currency.",
    ],
    calculationVersion: 1,
    citations: [
      {
        authorityClass: "authoritative",
        label: "EU passenger-car fuel consumption convention (litres per 100 kilometres)",
        reviewedDate: "2026-07-16",
        url: "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:31999L0094",
      },
    ],
    formulaSteps: [
      "Multiply the one-way distance by one for a one-way journey or two for a return journey.",
      "Multiply journey distance by L/100 km consumption, then divide by 100 to get litres required.",
      "Multiply litres required by the entered price per litre.",
      "Add the entered whole-journey toll cost.",
      "Divide total trip cost equally by the number of people entered.",
    ],
    freshnessExpectation: "No live rates are stored; users supply current fuel and toll prices for each calculation.",
    limitations: [
      "This is a planning estimate, not a guarantee of actual fuel use or cost.",
      "Parking, maintenance, depreciation, insurance and other travel costs are excluded.",
      "Actual consumption varies with traffic, speed, terrain, weather, load and driving style.",
    ],
    methodologyVersion: 1,
    reviewedDate: "2026-07-16",
    summary: "Estimate fuel and trip cost from one-way distance, L/100 km consumption, price per litre, journey type, total tolls and equal passenger splitting.",
    workedExamples: [
      "A 200 km return trip at 6 L/100 km uses 24 L. At 1.50 per litre with 12 in total tolls, the trip costs 48; split between three people, that is 16 each.",
    ],
  },
  methodologyVersion: 1,
  outputs: [
    { id: "fuel-required", label: "Fuel required", unit: "L" },
    { id: "fuel-cost", label: "Fuel cost", unit: "input currency" },
    { id: "total-trip-cost", label: "Total trip cost", unit: "input currency" },
    { id: "cost-per-passenger", label: "Cost per passenger", unit: "input currency" },
  ],
  reviewAuthority: "Youtoola owner",
  reviewedDate: "2026-07-16",
  riskProfile: "standard",
  supportedUnits: ["km", "L/100 km", "litre", "input currency"],
  utilityId: "fuel-trip-calculator",
  warnings: ["Use current values for your route and vehicle; Youtoola does not supply live prices or tolls."],
} satisfies UtilityDefinition;
